<a href="https://colab.research.google.com/github/codingA29/DataCleansing/blob/main/Data_Cleansing_Pasien_Rumah_Sakit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
file_path = "/content/drive/MyDrive/Dataset_Pasien_Latihan_Data_Cleansing.xlsx"

In [ ]:
import pandas as pd

df = pd.read_excel(
    file_path,
    sheet_name="Dataset Mentah"
)

display(df)

   ID Pasien        Nama Pasien  Umur       Diagnosis   Status Rawat
0      PS001       Andi Saputra  25.0  Penyakit Dalam    Rawat Jalan
1      PS002        Siti Aisyah  34.0         Jantung     Rawat Inap
2      PS003       Budi Santoso  47.0  Bedah/Ortopedi    Rawat Jalan
3      PS004       Rina Marlina  19.0         Infeksi    Rawat Jalan
4      PS005     Dedi Kurniawan  58.0           Saraf     Rawat Inap
5      PS006        Nadia Putri   8.0         Infeksi    Rawat Jalan
6      PS007      Agus Setiawan  68.0         Jantung     Rawat Inap
7      PS008          Lina Wati  42.0  Penyakit Dalam    Rawat Jalan
8      PS009       Rudi Hartono  55.0           Saraf     Rawat Inap
9      PS010          Maya Sari  31.0  Bedah/Ortopedi    Rawat Jalan
10     PS011      Fajar Hidayat  29.0          Jantng    Rawat Jalan
11     PS012       Dewi Lestari   NaN  Penyakit Dalam     Rawat Inap
12     PS013    Rizky Maulana    17.0         Infeksi    Rawat Jalan
13     PS014      Nurul Hidayah  73.0           Saraf     Rawat Inap
14     PS015       Tono Suharto  39.0  bedah/ortopedi    Rawat Jalan
15     PS016    Fitri Handayani  45.0         Jantung     rawat inap
16     PS017        Asep Rahmat  22.0         Infeksi    Rawat Jalan
17     PS018       Yuni Kartika  36.0  Penyakit Dalam    RAWAT JALAN
18     PS019       Dian Pratama  -4.0           Saraf     Rawat Inap
19     PS020         Ratna Dewi  61.0         Jantung     Rawat Inap
20     PS021     Hendra Gunawan  50.0  Bedah/Ortopedi    Rawat Jalan
21     PS022      Indah Permata  27.0         Infeksi    Rawat Jalan
22     PS023      Wahyu Nugroho  44.0             NaN     Rawat Inap
23     PS024        Nina Amelia  33.0  Penyakit Dalam    Rawat Jalan
24     PS025       Eko Prasetyo  52.0         Jantung     Rawat Inap
25     PS026       Sarah Anjani  16.0         Infeksi   Rawat Jalan
26     PS027        Joko Susilo  64.0           Saraf     Rawat Inap
27     PS028       Mila Karmila  40.0  Penyakit dalam    Rawat Jalan
28     PS029    Arif Firmansyah  28.0  Bedah/Ortopedi    Rawat Jalan
29     PS029    Arif Firmansyah  28.0  Bedah/Ortopedi    Rawat Jalan

In [ ]:
# Melihat ukuran dataset
print("Jumlah baris dan kolom:", df.shape)

# Melihat informasi dataset
print("\nInformasi Dataset:")
df.info()

Jumlah baris dan kolom: (30, 5)

Informasi Dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID Pasien     30 non-null     object
 1   Nama Pasien   30 non-null     object
 2   Umur          29 non-null     float64
 3   Diagnosis     29 non-null     object
 4   Status Rawat  30 non-null     object
dtypes: float64(1), object(4)
memory usage: 1.3+ KB

In [ ]:
# Mengecek jumlah missing value pada setiap kolom
print("Jumlah Missing Value:")
print(df.isnull().sum())

Jumlah Missing Value:
ID Pasien       0
Nama Pasien     0
Umur            1
Diagnosis       1
Status Rawat    0
dtype: int64

In [ ]:
# Menampilkan data yang memiliki nilai kosong
data_missing = df[df.isnull().any(axis=1)]

print("Data yang memiliki Missing Value:")
display(data_missing)

Data yang memiliki Missing Value:

   ID Pasien    Nama Pasien  Umur       Diagnosis Status Rawat
11     PS012   Dewi Lestari   NaN  Penyakit Dalam   Rawat Inap
22     PS023  Wahyu Nugroho  44.0             NaN   Rawat Inap

In [ ]:
# Mengisi missing value pada Umur dengan nilai median
median_umur = df["Umur"].median()
df["Umur"] = df["Umur"].fillna(median_umur)

# Mengisi missing value pada Diagnosis dengan nilai modus
modus_diagnosis = df["Diagnosis"].mode()[0]
df["Diagnosis"] = df["Diagnosis"].fillna(modus_diagnosis)

print("Median Umur:", median_umur)
print("Modus Diagnosis:", modus_diagnosis)

print("\nJumlah Missing Value Setelah Cleansing:")
print(df.isnull().sum())

Median Umur: 36.0
Modus Diagnosis: Infeksi

Jumlah Missing Value Setelah Cleansing:
ID Pasien       0
Nama Pasien     0
Umur            0
Diagnosis       0
Status Rawat    0
dtype: int64

In [ ]:
# Menampilkan kembali data PS012 dan PS023
display(
    df[df["ID Pasien"].isin(["PS012", "PS023"])]
)

   ID Pasien    Nama Pasien  Umur       Diagnosis Status Rawat
11     PS012   Dewi Lestari  36.0  Penyakit Dalam   Rawat Inap
22     PS023  Wahyu Nugroho  44.0         Infeksi   Rawat Inap

In [ ]:
print("Total Missing Value:", df.isnull().sum().sum())

Total Missing Value: 0

In [ ]:
# Mengecek jumlah data duplikat
jumlah_duplikat = df.duplicated().sum()

print("Jumlah Data Duplikat:", jumlah_duplikat)

Jumlah Data Duplikat: 1

In [ ]:
# Menampilkan semua data yang terduplikasi
data_duplikat = df[df.duplicated(keep=False)]

print("Data yang Terduplikasi:")
display(data_duplikat)

Data yang Terduplikasi:

   ID Pasien      Nama Pasien  Umur       Diagnosis Status Rawat
28     PS029  Arif Firmansyah  28.0  Bedah/Ortopedi  Rawat Jalan
29     PS029  Arif Firmansyah  28.0  Bedah/Ortopedi  Rawat Jalan

In [ ]:
# Menghapus data duplikat
df = df.drop_duplicates()

print("Data duplikat berhasil dihapus")

Data duplikat berhasil dihapus

In [ ]:
# Mengecek kembali data duplikat
print("Jumlah Duplikat Setelah Cleansing:", df.duplicated().sum())

print("Jumlah Data Setelah Duplikat Dihapus:", len(df))

Jumlah Duplikat Setelah Cleansing: 0
Jumlah Data Setelah Duplikat Dihapus: 29

In [ ]:
# Mengecek nilai unik sebelum standardisasi

print("Data Unik Diagnosis:")
print(df["Diagnosis"].unique())

print("\nData Unik Status Rawat:")
print(df["Status Rawat"].unique())

Data Unik Diagnosis:
['Penyakit Dalam' 'Jantung' 'Bedah/Ortopedi' 'Infeksi' 'Saraf' 'Jantng'
 'bedah/ortopedi' 'Penyakit dalam']

Data Unik Status Rawat:
['Rawat Jalan' 'Rawat Inap' 'rawat inap' 'RAWAT JALAN' ' Rawat Jalan ']

In [ ]:
# Membersihkan spasi berlebih pada kolom teks

kolom_teks = [
    "ID Pasien",
    "Nama Pasien",
    "Diagnosis",
    "Status Rawat"
]

for kolom in kolom_teks:
    df[kolom] = df[kolom].str.strip()

print("Spasi berlebih berhasil dibersihkan.")

Spasi berlebih berhasil dibersihkan.

In [ ]:
# Menyeragamkan format penulisan data

df["ID Pasien"] = df["ID Pasien"].str.upper()
df["Nama Pasien"] = df["Nama Pasien"].str.title()
df["Diagnosis"] = df["Diagnosis"].str.title()
df["Status Rawat"] = df["Status Rawat"].str.title()

print("Standardisasi format teks berhasil dilakukan.")

Standardisasi format teks berhasil dilakukan.

In [ ]:
print("Diagnosis Setelah Standardisasi:")
print(df["Diagnosis"].unique())

print("\nStatus Rawat Setelah Standardisasi:")
print(df["Status Rawat"].unique())

Diagnosis Setelah Standardisasi:
['Penyakit Dalam' 'Jantung' 'Bedah/Ortopedi' 'Infeksi' 'Saraf' 'Jantng']

Status Rawat Setelah Standardisasi:
['Rawat Jalan' 'Rawat Inap']

In [ ]:
# Memperbaiki kesalahan penulisan diagnosis

df["Diagnosis"] = df["Diagnosis"].replace({
    "Jantng": "Jantung"
})

print("Diagnosis Setelah Perbaikan Typo:")
print(df["Diagnosis"].unique())

Diagnosis Setelah Perbaikan Typo:
['Penyakit Dalam' 'Jantung' 'Bedah/Ortopedi' 'Infeksi' 'Saraf']

In [ ]:
# Menentukan kategori diagnosis yang valid

diagnosis_valid = [
    "Penyakit Dalam",
    "Jantung",
    "Bedah/Ortopedi",
    "Infeksi",
    "Saraf"
]

diagnosis_tidak_valid = df[
    ~df["Diagnosis"].isin(diagnosis_valid)
]

print("Jumlah Diagnosis Tidak Valid:",
      len(diagnosis_tidak_valid))

display(diagnosis_tidak_valid)

Jumlah Diagnosis Tidak Valid: 0

Empty DataFrame
Columns: [ID Pasien, Nama Pasien, Umur, Diagnosis, Status Rawat]
Index: []

In [ ]:
# Menentukan kategori status rawat yang valid

status_valid = [
    "Rawat Jalan",
    "Rawat Inap"
]

status_tidak_valid = df[
    ~df["Status Rawat"].isin(status_valid)
]

print("Jumlah Status Rawat Tidak Valid:",
      len(status_tidak_valid))

display(status_tidak_valid)

Jumlah Status Rawat Tidak Valid: 0

Empty DataFrame
Columns: [ID Pasien, Nama Pasien, Umur, Diagnosis, Status Rawat]
Index: []

In [ ]:
# Mengecek umur pasien yang tidak valid

umur_tidak_valid = df[
    (df["Umur"] < 8) |
    (df["Umur"] > 68)
]

print("Data dengan Umur Tidak Valid:")
display(umur_tidak_valid)

Data dengan Umur Tidak Valid:

   ID Pasien    Nama Pasien  Umur Diagnosis Status Rawat
13     PS014  Nurul Hidayah  73.0     Saraf   Rawat Inap
18     PS019   Dian Pratama  -4.0     Saraf   Rawat Inap

In [ ]:
# ==========================================
# PROSES FINAL DATA CLEANSING
# ==========================================

# 1. Menghapus data dengan umur tidak valid
df = df[
    (df["Umur"] >= 8) &
    (df["Umur"] <= 68)
]

# 2. Reset index
df = df.reset_index(drop=True)

# 3. Menampilkan dataset bersih
print("=== DATASET HASIL DATA CLEANSING ===")
print("Jumlah Data Bersih:", len(df))

display(df)

=== DATASET HASIL DATA CLEANSING ===
Jumlah Data Bersih: 27

   ID Pasien      Nama Pasien  Umur       Diagnosis Status Rawat
0      PS001     Andi Saputra  25.0  Penyakit Dalam  Rawat Jalan
1      PS002      Siti Aisyah  34.0         Jantung   Rawat Inap
2      PS003     Budi Santoso  47.0  Bedah/Ortopedi  Rawat Jalan
3      PS004     Rina Marlina  19.0         Infeksi  Rawat Jalan
4      PS005   Dedi Kurniawan  58.0           Saraf   Rawat Inap
5      PS006      Nadia Putri   8.0         Infeksi  Rawat Jalan
6      PS007    Agus Setiawan  68.0         Jantung   Rawat Inap
7      PS008        Lina Wati  42.0  Penyakit Dalam  Rawat Jalan
8      PS009     Rudi Hartono  55.0           Saraf   Rawat Inap
9      PS010        Maya Sari  31.0  Bedah/Ortopedi  Rawat Jalan
10     PS011    Fajar Hidayat  29.0         Jantung  Rawat Jalan
11     PS012     Dewi Lestari  36.0  Penyakit Dalam   Rawat Inap
12     PS013    Rizky Maulana  17.0         Infeksi  Rawat Jalan
13     PS015     Tono Suharto  39.0  Bedah/Ortopedi  Rawat Jalan
14     PS016  Fitri Handayani  45.0         Jantung   Rawat Inap
15     PS017      Asep Rahmat  22.0         Infeksi  Rawat Jalan
16     PS018     Yuni Kartika  36.0  Penyakit Dalam  Rawat Jalan
17     PS020       Ratna Dewi  61.0         Jantung   Rawat Inap
18     PS021   Hendra Gunawan  50.0  Bedah/Ortopedi  Rawat Jalan
19     PS022    Indah Permata  27.0         Infeksi  Rawat Jalan
20     PS023    Wahyu Nugroho  44.0         Infeksi   Rawat Inap
21     PS024      Nina Amelia  33.0  Penyakit Dalam  Rawat Jalan
22     PS025     Eko Prasetyo  52.0         Jantung   Rawat Inap
23     PS026     Sarah Anjani  16.0         Infeksi  Rawat Jalan
24     PS027      Joko Susilo  64.0           Saraf   Rawat Inap
25     PS028     Mila Karmila  40.0  Penyakit Dalam  Rawat Jalan
26     PS029  Arif Firmansyah  28.0  Bedah/Ortopedi  Rawat Jalan

In [ ]:
# Menyimpan dataset bersih ke Google Drive

output_path = (
    "/content/drive/MyDrive/"
    "Dataset_Pasien_Hasil_Cleansing.xlsx"
)

df.to_excel(
    output_path,
    index=False
)

print("Dataset bersih berhasil disimpan.")
print("Lokasi file:")
print(output_path)

Dataset bersih berhasil disimpan.
Lokasi file:
/content/drive/MyDrive/Dataset_Pasien_Hasil_Cleansing.xlsx

In [ ]:
import pandas as pd

file_path = (
    "/content/drive/MyDrive/"
    "Dataset_Pasien_Hasil_Cleansing.xlsx"
)

df = pd.read_excel(file_path)

print("Dataset berhasil dibaca.")
display(df)

Dataset berhasil dibaca.

   ID Pasien      Nama Pasien  Umur       Diagnosis Status Rawat
0      PS001     Andi Saputra    25  Penyakit Dalam  Rawat Jalan
1      PS002      Siti Aisyah    34         Jantung   Rawat Inap
2      PS003     Budi Santoso    47  Bedah/Ortopedi  Rawat Jalan
3      PS004     Rina Marlina    19         Infeksi  Rawat Jalan
4      PS005   Dedi Kurniawan    58           Saraf   Rawat Inap
5      PS006      Nadia Putri     8         Infeksi  Rawat Jalan
6      PS007    Agus Setiawan    68         Jantung   Rawat Inap
7      PS008        Lina Wati    42  Penyakit Dalam  Rawat Jalan
8      PS009     Rudi Hartono    55           Saraf   Rawat Inap
9      PS010        Maya Sari    31  Bedah/Ortopedi  Rawat Jalan
10     PS011    Fajar Hidayat    29         Jantung  Rawat Jalan
11     PS012     Dewi Lestari    36  Penyakit Dalam   Rawat Inap
12     PS013    Rizky Maulana    17         Infeksi  Rawat Jalan
13     PS015     Tono Suharto    39  Bedah/Ortopedi  Rawat Jalan
14     PS016  Fitri Handayani    45         Jantung   Rawat Inap
15     PS017      Asep Rahmat    22         Infeksi  Rawat Jalan
16     PS018     Yuni Kartika    36  Penyakit Dalam  Rawat Jalan
17     PS020       Ratna Dewi    61         Jantung   Rawat Inap
18     PS021   Hendra Gunawan    50  Bedah/Ortopedi  Rawat Jalan
19     PS022    Indah Permata    27         Infeksi  Rawat Jalan
20     PS023    Wahyu Nugroho    44         Infeksi   Rawat Inap
21     PS024      Nina Amelia    33  Penyakit Dalam  Rawat Jalan
22     PS025     Eko Prasetyo    52         Jantung   Rawat Inap
23     PS026     Sarah Anjani    16         Infeksi  Rawat Jalan
24     PS027      Joko Susilo    64           Saraf   Rawat Inap
25     PS028     Mila Karmila    40  Penyakit Dalam  Rawat Jalan
26     PS029  Arif Firmansyah    28  Bedah/Ortopedi  Rawat Jalan

In [ ]:
def kelompok_umur(umur):
    if umur <= 12:
        return "Anak"
    elif umur <= 17:
        return "Remaja"
    elif umur <= 59:
        return "Dewasa"
    else:
        return "Lansia"

In [ ]:
df["Kelompok Umur"] = df["Umur"].apply(kelompok_umur)

print("Kolom Kelompok Umur berhasil ditambahkan.")

Kolom Kelompok Umur berhasil ditambahkan.

In [ ]:
print("=== HASIL DATA ENRICHMENT ===")

display(df)

=== HASIL DATA ENRICHMENT ===

   ID Pasien      Nama Pasien  Umur       Diagnosis Status Rawat Kelompok Umur
0      PS001     Andi Saputra    25  Penyakit Dalam  Rawat Jalan        Dewasa
1      PS002      Siti Aisyah    34         Jantung   Rawat Inap        Dewasa
2      PS003     Budi Santoso    47  Bedah/Ortopedi  Rawat Jalan        Dewasa
3      PS004     Rina Marlina    19         Infeksi  Rawat Jalan        Dewasa
4      PS005   Dedi Kurniawan    58           Saraf   Rawat Inap        Dewasa
5      PS006      Nadia Putri     8         Infeksi  Rawat Jalan          Anak
6      PS007    Agus Setiawan    68         Jantung   Rawat Inap        Lansia
7      PS008        Lina Wati    42  Penyakit Dalam  Rawat Jalan        Dewasa
8      PS009     Rudi Hartono    55           Saraf   Rawat Inap        Dewasa
9      PS010        Maya Sari    31  Bedah/Ortopedi  Rawat Jalan        Dewasa
10     PS011    Fajar Hidayat    29         Jantung  Rawat Jalan        Dewasa
11     PS012     Dewi Lestari    36  Penyakit Dalam   Rawat Inap        Dewasa
12     PS013    Rizky Maulana    17         Infeksi  Rawat Jalan        Remaja
13     PS015     Tono Suharto    39  Bedah/Ortopedi  Rawat Jalan        Dewasa
14     PS016  Fitri Handayani    45         Jantung   Rawat Inap        Dewasa
15     PS017      Asep Rahmat    22         Infeksi  Rawat Jalan        Dewasa
16     PS018     Yuni Kartika    36  Penyakit Dalam  Rawat Jalan        Dewasa
17     PS020       Ratna Dewi    61         Jantung   Rawat Inap        Lansia
18     PS021   Hendra Gunawan    50  Bedah/Ortopedi  Rawat Jalan        Dewasa
19     PS022    Indah Permata    27         Infeksi  Rawat Jalan        Dewasa
20     PS023    Wahyu Nugroho    44         Infeksi   Rawat Inap        Dewasa
21     PS024      Nina Amelia    33  Penyakit Dalam  Rawat Jalan        Dewasa
22     PS025     Eko Prasetyo    52         Jantung   Rawat Inap        Dewasa
23     PS026     Sarah Anjani    16         Infeksi  Rawat Jalan        Remaja
24     PS027      Joko Susilo    64           Saraf   Rawat Inap        Lansia
25     PS028     Mila Karmila    40  Penyakit Dalam  Rawat Jalan        Dewasa
26     PS029  Arif Firmansyah    28  Bedah/Ortopedi  Rawat Jalan        Dewasa

In [ ]:
print("Jumlah Pasien Berdasarkan Kelompok Umur:")

print(df["Kelompok Umur"].value_counts())

Jumlah Pasien Berdasarkan Kelompok Umur:
Kelompok Umur
Dewasa    21
Lansia     3
Remaja     2
Anak       1
Name: count, dtype: int64

In [ ]:
output_path = (
    "/content/drive/MyDrive/"
    "Dataset_Pasien_Hasil_Enrichment.xlsx"
)

df.to_excel(
    output_path,
    index=False
)

print("Dataset hasil enrichment berhasil disimpan.")
print("Lokasi file:", output_path)

Dataset hasil enrichment berhasil disimpan.
Lokasi file: /content/drive/MyDrive/Dataset_Pasien_Hasil_Enrichment.xlsx